### ISSUE TITLE
Icons size

### ISSUE THREAD

**Issue by arnofly** [Chris2011/QuickOpener-NetBeans#2]
Hi,
Nice new icons pack, but always shown in small size, even if "Small Toolbar Icons" option is not checked. Same bug with NetBeans v10 or v11.

![nb10-quickopener-screen](https://user-images.githubusercontent.com/45882853/58380529-96a7db00-7fb2-11e9-839e-1b7ac129d428.png)
![nb11-quickopener-screen](https://user-images.githubusercontent.com/45882853/58380538-9dcee900-7fb2-11e9-9a4f-b88e0665089c.png)

The commands button is not impacted.

![nb11-quickopener-small-screen](https://user-images.githubusercontent.com/45882853/58380635-a1af3b00-7fb3-11e9-8f4a-8fccd85f5edb.png)

I don't know if it's an important information, but I run NetBeans on a 3440x1440 (WQHD) screen. Dell U3417W to be exact and it's a very good screen for quite small desk or graphists ;)

Thx

**Comment by Chris2011** [comment]
Thx, will have a look.

**Comment by Chris2011** [comment]
Fixed in 1.3.1. Thx for report :)
