### ISSUE TITLE
Add "Copy Path" option to files

### ISSUE THREAD

**Issue by negora** [Chris2011/QuickOpener-NetBeans#3]
In the `Projects` panel, when I click with the right button on a directory or package, a contextual menu appears. In it, there is an option called `Copy Path` that copies the path of such directory. In my opinion, it would be useful if such option also existed for files.

Right now, there is only the option `Open in Default App`. So, if I want to copy the path of the file, I've to open it in the editor panel, open the contextual menu of the tab, and then click  on `Copy File Path`.

I take this opportunity to thank you for such an useful plug-in.

**Comment by Chris2011** [comment]
Thx, but I'm only a contributor. I'm not the original author of the plugin :). Thx for the ticket, sounds legit to me.

**Comment by Chris2011** [comment]
The thing is, it is already possible via the shortcut. For me it is "Alt + 3". So if you select the file, hit the shortcut, the path of the file will be copied. But yeah it should be also a context menu entry for the file.

**Comment by negora** [comment]
> Thx, but I'm only a contributor. I'm not the original author of the plugin :). Thx for the ticket, sounds legit to me.

Hi Chris ;) . I think that I know you from the `Issues` section of the [Everlaw's NetBeans TypeScript repository](https://github.com/Everlaw/nbts).



> The thing is, it is already possible via the shortcut. For me it is "Alt + 3". So if you select the file, hit the shortcut, the path of the file will be copied. But yeah it should be also a context menu entry for the file.

Touché, he he he. I don't know how I couldn't realize about that. I can map such shortcut to a mouse action with "imwheel" (in Linux), and be even more productive.

In addition to that, I've seen that there's another (obvious) workaround: using the corresponding button of the top toolbar. It makes me move the pointer of the mouse far away from the file position, but it works fine too.

Thank you!

**Comment by Chris2011** [comment]
I will add such feature later for copy path for files too.

**Comment by Chris2011** [comment]
Fixed in version 1.4.0. Only available here atm. Will uploaded soon to the plugin portal.
