### ISSUE TITLE
Error message about "org-pr-nb-plugins-usd-*.shadow:

### ISSUE THREAD

**Issue by hupfdule** [Chris2011/QuickOpener-NetBeans#4]
QuickOpener Plugin: 1.3.1
Netbeans: 11.0
Operating System: Debian Buster
Desktop Environmen: Enlightenment E22 (0.22.4)

After installing the QuickOpener plugin in Netbeans 11.0 on I get 4 error dialogs each time after starting netbeans:

![error](https://user-images.githubusercontent.com/36069345/60886728-00263500-a253-11e9-93c6-76b8a64979a8.png)

The same for 
- `MailWithSystem.shadow`
- `OpenWithSystem.shadow`
- `EditWithSystem.shadow`
- `BrowseWithSystem.shadow`

Interestingly, the functions `Open in Terminal` and `Open in File Manager` don't do anything, but `Open in Default App` works correctly.

**Comment by hupfdule** [comment]
Just noticed that you release version 1.4.0. I tried it with that version and the problem stays the same.

**Comment by Chris2011** [comment]
Hi, thx for the report. Is it possible for you, that you can check it with another Debian? maybe a version before? Or with ubuntu or any other linux? Will check it later too. I use Windows, so I need a VM for that.

**Comment by hupfdule** [comment]
When trying to do so I found out that this is a conflict with another plugin I had installed: [Netbeans Use System Desktop](http://plugins.netbeans.org/plugin/57462/netbeans-use-system-desktop).

After deactivating that plugin, the error dialogs disappear. Maybe they aren't event triggered by "QuickOpener", but instead "Netbeans use System Desktop".

As I like your approach better, I just deinstalled the other plugin. But maybe you should document that conflict or, if netbeans allows such a thing, prohibit the installation if that other plugin is active.

**Comment by Chris2011** [comment]
It depends on you, what you like, you can use whatever you want. But yeah, using two plugins, which makes the same doesn't make any sense. We also have some other plugin that could be in conflict with this one. Didn't noticed it yet. But thx for figure it out :) will document it later.
